server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: library_security
  datasource:
    username: 'unforgettable'
    password: '27092100'
    url: jdbc:postgresql://localhost:5432/library_security
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/library_security
    user: 'unforgettable'
    password: '27092100'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

jwt:
  secretKey: 'SuperBombaClassUltraProtectedSecretKeyForMoneyIs'
  accessTokenExpirationAfterMinutes: 1000
  refreshTokenExpirationAfterWeeks: 2